made the placeholder of the tooltip fillable from config
kommitters/editorjs-tooltip pull request #117
Opened 2024-01-04 19:40 UTC by abdelhamiderrahmouni

2024-01-04 21:28 UTC, miguelnietoa requested changes
@abdelhamiderrahmouni thanks for this great contribution! Allowing to customize the input's placeholder is very useful! 👏🏻 

Could you please make sure to include the `placeholder` parameter in both the **Usage** and **Config Params** sections of the README file?

2024-01-04 21:28 UTC, miguelnietoa commented on src/index.js
> +    this.inputPlaceholder = config.placeholder ? config.placeholder : "Add a tooltip";
@abdelhamiderrahmouni I have some suggestions to follow style guides used in the project:

- We could take advantage of the nullish coalescing operator (`??`)
- Consider using single quotes for the default value
- How about renaming `this.inputPlaceholder` to `this.placeholder` for consistency?

```suggestion
    this.placeholder = config.placeholder ?? 'Add a tooltip';
```

Would you mind applying the nullish coalescing operator on lines 42 and 45 as well? 🙌🏻

2024-01-05 13:42 UTC, abdelhamiderrahmouni commented
> @abdelhamiderrahmouni thanks for this great contribution! Allowing to customize the input's placeholder is very useful! 👏🏻
> 
> Could you please make sure to include the `placeholder` parameter in both the **Usage** and **Config Params** sections of the README file?
Sure i would be happy to.

2024-02-19 20:50 UTC, miguelnietoa approved these changes

2024-02-19 20:53 UTC, MarioRodriguezS approved these changes

2024-02-19 20:53 UTC, miguelnietoa commented
Hey @abdelhamiderrahmouni, I moved forward with the suggested changes in order to release this feature as soon as possible 🚀

2024-02-19 20:57 UTC, merged

2024-02-19 21:59 UTC, miguelnietoa commented
@abdelhamiderrahmouni We just released [`v1.2.0`](https://github.com/kommitters/editorjs-tooltip/releases/tag/v1.2.0) which includes this new `placeholder` option. Thanks for contributing! 💯